NO_BREAK_LABEL = 0
TRUE_BREAK_START_LABEL = 1
TRUE_BREAK_MID_LABEL = 2
TRUE_BREAK_END_LABEL = 3
FAKE_BREAK_START_LABEL = 4
FAKE_BREAK_MID_LABEL = 5
FAKE_BREAK_END_LABEL = 6

BREAK_LABEL = 'break_label'
TAKE_PROFIT_LABEL = 'take_profit_label'
