# Bolling Bands
BOLLING_UPPER = 'Upper'
BOLLING_MIDDLE = 'Middle'
BOLLING_LOWER = 'Lower'

BOLLING_UPPER_B = 'Upper_B'
BOLLING_MIDDLE_B = 'Middle_B'
BOLLING_LOWER_B = 'Lower_B'


# MACD
MACD = 'MACD'
MACD_SIGNAL = 'MACD Signal'
MACD_HIST = 'MACD Hist'

# RSI
RSI = 'RSI'

# KD
K = 'K'
D = 'D'

# EMA
EMA = 'EMA'

# WMA
WMA = 'WMA'

# ADX
ADX = 'ADX'

# OBV
OBV = 'OBV'

# Ichimoku Clouds
ICHIMOKU_TENKANSEN = 'ichimoku_tenkansen'
ICHIMOKU_KIJUNSEN = 'ichimoku_kijunsen'
ICHIMOKU_SENKOU_A = 'ichimoku_senkou_a'
ICHIMOKU_SENKOU_B = 'ichimoku_senkou_b'
ICHIMOKU_CHIKOU = 'ichimoku_chikou'

# Pattern
CDL2CROWS = 'CDL2CROWS'
CDL3BLACKCROWS = 'CDL3BLACKCROWS'
CDL3INSIDE = 'CDL3INSIDE'
CDL3LINESTRIKE = 'CDL3LINESTRIKE'
CDL3OUTSIDE = 'CDL3OUTSIDE'
CDL3STARSINSOUTH = 'CDL3STARSINSOUTH'
CDL3WHITESOLDIERS = 'CDL3WHITESOLDIERS'
CDLABANDONEDBABY = 'CDLABANDONEDBABY'
CDLADVANCEBLOCK = 'CDLADVANCEBLOCK'
CDLBELTHOLD = 'CDLBELTHOLD'
CDLBREAKAWAY = 'CDLBREAKAWAY'
CDLCLOSINGMARUBOZU = 'CDLCLOSINGMARUBOZU'
CDLCONCEALBABYSWALL = 'CDLCONCEALBABYSWALL'
CDLCOUNTERATTACK = 'CDLCOUNTERATTACK'
CDLDARKCLOUDCOVER = 'CDLDARKCLOUDCOVER'
CDLDOJI = 'CDLDOJI'
CDLDOJISTAR = 'CDLDOJISTAR'
CDLDRAGONFLYDOJI = 'CDLDRAGONFLYDOJI'
CDLENGULFING = 'CDLENGULFING'
CDLEVENINGDOJISTAR = 'CDLEVENINGDOJISTAR'
CDLEVENINGSTAR = 'CDLEVENINGSTAR'
CDLGAPSIDESIDEWHITE = 'CDLGAPSIDESIDEWHITE'
CDLGRAVESTONEDOJI = 'CDLGRAVESTONEDOJI'
CDLHAMMER = 'CDLHAMMER'
CDLHANGINGMAN = 'CDLHANGINGMAN'
CDLHARAMI = 'CDLHARAMI'
CDLHARAMICROSS = 'CDLHARAMICROSS'
CDLHIGHWAVE = 'CDLHIGHWAVE'
CDLHIKKAKE = 'CDLHIKKAKE'
CDLHIKKAKEMOD = 'CDLHIKKAKEMOD'
CDLHOMINGPIGEON = 'CDLHOMINGPIGEON'
CDLIDENTICAL3CROWS = 'CDLIDENTICAL3CROWS'
CDLINNECK = 'CDLINNECK'
CDLINVERTEDHAMMER = 'CDLINVERTEDHAMMER'
CDLKICKING = 'CDLKICKING'
CDLKICKINGBYLENGTH = 'CDLKICKINGBYLENGTH'
CDLLADDERBOTTOM = 'CDLLADDERBOTTOM'
CDLLONGLEGGEDDOJI = 'CDLLONGLEGGEDDOJI'
CDLLONGLINE = 'CDLLONGLINE'
CDLMARUBOZU = 'CDLMARUBOZU'
CDLMATCHINGLOW = 'CDLMATCHINGLOW'
CDLMATHOLD = 'CDLMATHOLD'
CDLMORNINGDOJISTAR = 'CDLMORNINGDOJISTAR'
CDLMORNINGSTAR = 'CDLMORNINGSTAR'
CDLONNECK = 'CDLONNECK'
CDLPIERCING = 'CDLPIERCING'
CDLRICKSHAWMAN = 'CDLRICKSHAWMAN'
CDLRISEFALL3METHODS = 'CDLRISEFALL3METHODS'
CDLSEPARATINGLINES = 'CDLSEPARATINGLINES'
CDLSHOOTINGSTAR = 'CDLSHOOTINGSTAR'
CDLSHORTLINE = 'CDLSHORTLINE'
CDLSPINNINGTOP = 'CDLSPINNINGTOP'
CDLSTALLEDPATTERN = 'CDLSTALLEDPATTERN'
CDLSTICKSANDWICH = 'CDLSTICKSANDWICH'
CDLTAKURI = 'CDLTAKURI'
CDLTASUKIGAP = 'CDLTASUKIGAP'
CDLTHRUSTING = 'CDLTHRUSTING'
CDLTRISTAR = 'CDLTRISTAR'
CDLUNIQUE3RIVER = 'CDLUNIQUE3RIVER'
CDLUPSIDEGAP2CROWS = 'CDLUPSIDEGAP2CROWS'
CDLXSIDEGAP3METHODS = 'CDLXSIDEGAP3METHODS'
